### PR TITLE
Major overhaul to building the images

### PR DESCRIPTION
**Pull request by longr**
This PR merges in @mabraham changes and builds on them.  Instead of needing 2 repositories (with an unclear manual/automatic build system) this automates the build process.  The building of the containers has been outsourced to github-actions instead of dockerhub. This provides increased flexibility, parallelization and increased stability of the build chain.  

The container is split into four builds (as per Mark's changes), one for each simd-type. The new change is that the CI will build these in parallel and register each to dockerhub.  Once this is complete, the final stage combines all images together - (using Mark's Dockerfile from before) and then registers the final image to Dockerhub.  This workflow is documented in the README file under "Contributing".

This will require 2 changes to the current setup:
1) Automatic build on Dockerhub are disabled (we don't need it, and it will probably fail due to the setup)
2) A PAT (Personal Access Token) is generated for the user account that can modify the Dockerhub images.
3) That users user name is added as a GITHUB secret called DOCKER_USERNAME, and the PAT is added as another secret called DOCKER_PASSWORD on github.

This will allow the CI to register the changes to Dockerhub.

As I write this, I realise that I have not updated the paths for the containers in the root Dockerfile or the CI yaml, these still point to my dockerhub registry.  However, this is a minor point that can be changed later as the aim of this is to start the discussion about this overhaul of the workflow as much as it is designed to overhaul the workflow.

Robin.

### CODE REVIEW

**Comment by mabraham** [comment]
that sounds like good improvements. the separate repo was only ever about avoiding timeouts

**Comment by longr** [comment]
We had the same issue previously and got round it with a mess of hooks to chain docker builds together, but it was also unstable.  

@ahad3112, do you think we will be able to combine this with what you have been working on?  I was planning (perhaps next week now) to look at using artefacts to move the images between jobs.  This way we can get rid of one stage of registering, and perhaps even run some testing on the images before we upload and register them to docker.

**Comment by maaahad** [comment]
Hi Robin,
I just managed to have a look at the Mark's Recipe. Both his recipe and my recipe are quite similar. In both cases we are using HPCCM.  My recipe are doing the followings that are different from Mark's recipe:
1. My recipe generates a single Dockerfile that may contain multiple GMX built for different SIMD. 

2. My recipe allows the user to specify FFTW version, in case the user does not provide it, GROMCS will build FFTW from source.

3. I also allow the user to turn on/off RDTSCP instruction. I added this, because I found that if RDTSCP is turned on, I can't run GROMACS on my own machine though my machine support avx2 simd instruction set. 

4. If the User does not provide GMX configuration such as SIMD and RDTSCP, the recipe will identify the underlying SIMD to build GROMACS by default (Consider RDTSCP instruction set as well).

5. gmx_chooser will consider RDTSCP option along with sse2, avx, avx2, avx_512f of the underlying CPU to identify best possible gmx binary.

6. Users can also specify to perform a REGRESSION test for GROMACS during image build.
 
If you need to know more please use the following source:
source code: 
https://github.com/ahad3112/gromacs-hpccm-recipes-mult-stages

High level description on Implementation:
https://docs.google.com/document/d/11rDU7CB0hsZDpjwdyfr1rBFikXMsMYdbwvLpoldOze8/edit?usp=sharing

Users guide:
https://docs.google.com/document/d/1JyqtWeF7qqwZl8uiTT-x8SwCPQJJ1CxIxZzq1TIzq30/edit?usp=sharing

So, If you think you want to extend Mark’s recipe with any of the above, it can be done easily. Let me know what you think.
Thanks. 

Br,
Ahad

**Review by stain — APPROVED** [review]
I am glad @mabraham and @longr are in agreement! :)  

We could wait for @ahad3112's changes - but I think the only change needed right away is in the action's docker commants, `longr` -> `gromacs` (Docker Hub)  - could this also be parameterized?

As this would now be pushing the other way, from GitHub Action to Docker Hub, a Docker Hub account is needed to fill in the secrets for the GitHub Action.

I am making a new Docker Hub user called `bioexcelbuild` and, adding it to the `gromacs` organisation on Docker Hub I will set up this GitHub repo to have those tokens.

**Edit**: `bioexcelbuild` now set up and tokens added. Turned off Docker Hub automatic builds from GitHub.

**Comment by stain** [comment]
Perhaps make sure the workflow only runs from the `master` branch or that the branch name is reflected in the pushed tag.

**Comment by maaahad** [comment]
Hi @mabraham , @longr and @stain,
I updated version of the recipe https://github.com/longr/gromacs-docker.git. Unfortunate I can not push it to the git repo as I don't have permission. @longr Can you please provide me permission to push the update. 
What I did are as follows:
   1. Added option for fftw (--fftw). This option is optional, meaning that if the user does not provide  value for this option (version no.), GROMACs build will download and install FFTW from the source automatically. If the version is provided, that version of fftw will be used to build GROMACS.
   2. Added option for regression test (--regtest). This option is also not mandatory and if provided, a regression test will be performed for each GROMACS build. 
3.To capture the user input for fftw, I have added a function called merging_stage(args), whose responsibility is to generate the main Dockerfile that combines everything together dynamically rather than hardcoding the file. This is done using HPCCM’s primitives and building_blocks. This function is only called after building the last GMX engine (AVX_512). As the final Dockerfile is used after building all intermediate images for different SIMD instruction sets, CI should be able to use the updated version of the file based on users input for fftw, I guess. 

Consequence of providing fftw option:
   1. We have to repeat installing fftw for each SIMD instruction set.
   2. Good thing is that users can specify which version of fftw they would like to be used in GROMACS installation.

What can be done to avoid repetition:
   1. It is possible to use the Marks’s way of using another image to use the FFTW if the users provided fftw option. This way image building time can be reduced by trading off providing users option to specify fftw version.
   2. Or, we can use a single Dockerfile as I did on my version of recipe. More information on my recipe can be found here: 
https://docs.google.com/document/d/11rDU7CB0hsZDpjwdyfr1rBFikXMsMYdbwvLpoldOze8/edit
.

A note:
I can see that, gmx_chooser script only considers GROMACS engine named gmx, which should not be the case if MPI is enabled and if you used the GROMACS’s default naming convention for gmx engine. In case of mpi enabled, the engine name will be gmx_mpi. I handled this issue in my version of gmx_chooser script. 

Please let me know your feedback or if there anything I can do. Thanks.

Best Regards,
Ahad

**Pull request merged**
