### PR TITLE
Update to 2021.4 GROMACS

### PR DESCRIPTION
**Pull request by douglowe**
Building the 2021.4 GROMACS docker image.

### CODE REVIEW

**Comment by douglowe** [comment]
The build failure seems to be related to GMX_GPU - which is currently "ON", but apparently should be one of: "OFF", "CUDA", "OpenCL", or "SYCL". Is this a change in configuration options for version 2021?

**Comment by douglowe** [comment]
I've made a change to the build scripts to do correct the GMX_GPU flag: https://github.com/bioexcel/gromacs-hpccm-recipes-mult-stages/pull/3 - does this look reasonable?

**Comment by mabraham** [comment]
> The build failure seems to be related to GMX_GPU - which is currently "ON", but apparently should be one of: "OFF", "CUDA", "OpenCL", or "SYCL". Is this a change in configuration options for version 2021?

Yes, that changed

**Comment by douglowe** [comment]
We're now getting this error:
`GMXAPI requires position-independent code.  Set -DGMXAPI=OFF or -DBUILD_SHARED_LIBS=ON.`

I guess we aren't interested in providing the API in the docker image, and so can set `-DGMXAPI=OFF` in the build script?

**Comment by mabraham** [comment]
> We're now getting this error: `GMXAPI requires position-independent code. Set -DGMXAPI=OFF or -DBUILD_SHARED_LIBS=ON.`
> 
> I guess we aren't interested in providing the API in the docker image, and so can set `-DGMXAPI=OFF` in the build script?

Setting to prefer to find and link static libraries was a decision that mattered little at the time and may help e.g. gpu perf slightly. I think the impact of APIs like GMXAPI and NB-LIB being available is probably higher, so suggest we find and build shared libs that suit the APIs.

**Comment by douglowe** [comment]
> > We're now getting this error: `GMXAPI requires position-independent code. Set -DGMXAPI=OFF or -DBUILD_SHARED_LIBS=ON.`
> > I guess we aren't interested in providing the API in the docker image, and so can set `-DGMXAPI=OFF` in the build script?
> 
> Setting to prefer to find and link static libraries was a decision that mattered little at the time and may help e.g. gpu perf slightly. I think the impact of APIs like GMXAPI and NB-LIB being available is probably higher, so suggest we find and build shared libs that suit the APIs.

Sure thing - I'll give building the shared libraries a go.

**Comment by douglowe** [comment]
This build failed with a message about a missing manifest for the avx2 docker image - I suspect it might be a one-off so will trigger the build process again.

**Pull request merged**
